---

---

```{r}
#| echo: false
#| include: false

library(tidyverse)
library(gt)

# Color palette
color_palette <-
  c(
    "#040548",
    "#86C7ED",
    "#7A6C5D",
    "#A54657",
    "#EEF3F6"
  )

# Read in data from pins
# board <- pins::board_rsconnect(server = "connect.posit.it")

churn <- 
  read_csv("data/churn.csv") # |> 
  #pins::pin_read(board, "sara.altman/simulated_churn") # |> 
  # filter(product == params$product)

states <- read_rds("data/states.rds")
  #pins::pin_read(board, "sara.altman/states")
```

```{r}
#| echo: false
htmltools::img(
  src = knitr::image_uri("images/logo.png"), 
  alt = 'logo', 
  style = 'position:absolute; top:0; right:0; padding:30px; width:220px; height:220px'
)
```

## Overview

Understanding our customer churn is essential to DemoCo's success. In 2022, our customer churn was 15% - leading to revenue loss of \$2.2 million. **Our 2023 goal is for customer churn to be under 10%.**

## Churn by quarter

```{r}
#| echo: false
churn |> 
  group_by(year = year(date), quarter = quarter(date), reason) |> 
  summarize(total_churn = sum(churn), total = n(), .groups = "drop_last") |> 
  mutate(
    year_quarter_total = sum(total),
    percent_churn = total_churn / year_quarter_total
  ) |> 
  ungroup() |> 
  filter(!is.na(reason)) |> 
  mutate(reason = fct_reorder(reason, percent_churn, .desc = TRUE)) |> 
  ggplot(
    aes(
      glue::glue("{year} Q{quarter}"), 
      percent_churn, 
      color = reason
    )
  ) +
  geom_point() +
  geom_line(aes(group = reason)) +
  scale_color_manual(values = color_palette) +
  theme_minimal() +
  labs(
    x = "Quarter",
    y = "Percent churn",
    color = "Reason",
    title = "Percent churn by reason and quarter"
  )
```

## Contract type

```{r}
#| echo: false
churn |> 
  ggplot(aes(contract, last_purchase_days_ago, fill = churn)) +
  geom_boxplot() +
  scale_fill_manual(values = color_palette) +
  theme_minimal() +
  labs(
    x = "Contract type",
    y = "Days since last purchase",
    fill = "Churned",
    title = "Churn status by contract type and days since purchase"
  )
  
```

## Purchase characteristics

```{r}
#| echo: false
churn |>
  group_by(contract, churn) |>
  summarize(
    across(
      c(average_purchase_amount, total_transactions, last_purchase_days_ago),
      median
    ),
    .groups = "drop_last"
  ) |> 
  rename(
    `Average purchase` = average_purchase_amount,
    `Total transactions` = total_transactions,
    `Days since last purchase` = last_purchase_days_ago
  ) |> 
  mutate(churn = if_else(churn, "Churned", "Did not churn")) |> 
  gt::gt(rowname_col = "churn") |> 
  gtExtras::gt_highlight_rows(
    rows = churn == "Churned",
    fill = color_palette[[1]]
  ) |> 
  fmt_currency(columns = `Average purchase`) |> 
  fmt_integer(`Days since last purchase`) |> 
  tab_header(
    title = "Purchase characteristics by contract type and churn status"
  )
```
