title: "Customer Churn Report"
editor: visual
execute:
  echo: false
  warning: false
format:
  html:
    embed-resources: true
    smooth-scroll: true
    theme: sandstone
    mainfont: sans-serif
    fontsize: 1.4rem
    fontcolor: "#383a3c"
css: assets/custom.css

