title: "Customer Churn Report: `r params$product` product"
subtitle: "Updated: `r Sys.Date()`"
editor: visual
execute:
  echo: false
  warning: false
title-block-banner: "#EEF3F6"
title-block-banner-color: "#040548"
format:
  html:
    embed-resources: true
    smooth-scroll: true
    theme: sandstone
    mainfont: Open Sauce Sans
    monofont: Lato
    fontsize: 1.4rem
    fontcolor: "#040548"
css: custom.css

